#ifndef TEPX_VERIFIER_H
#define TEPX_VERIFIER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef TEPX_READER_H
#include "tepx_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int tepx_test_message_verify_table(flatcc_table_verifier_descriptor_t *td);

static int tepx_test_message_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* replica_id */)) return ret;
    return flatcc_verify_ok;
}

static inline int tepx_test_message_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, tepx_test_message_identifier, &tepx_test_message_verify_table);
}

static inline int tepx_test_message_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, tepx_test_message_type_identifier, &tepx_test_message_verify_table);
}

static inline int tepx_test_message_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &tepx_test_message_verify_table);
}

static inline int tepx_test_message_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &tepx_test_message_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* TEPX_VERIFIER_H */
