#ifndef TEPX_READER_H
#define TEPX_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct tepx_test_message_table *tepx_test_message_table_t;
typedef const flatbuffers_uoffset_t *tepx_test_message_vec_t;
typedef flatbuffers_uoffset_t *tepx_test_message_mutable_vec_t;
#ifndef tepx_test_message_identifier
#define tepx_test_message_identifier flatbuffers_identifier
#endif
#define tepx_test_message_type_hash ((flatbuffers_thash_t)0x19e85804)
#define tepx_test_message_type_identifier "\x04\x58\xe8\x19"



struct tepx_test_message_table { uint8_t unused__; };

static inline size_t tepx_test_message_vec_len(tepx_test_message_vec_t vec)
__flatbuffers_vec_len(vec)
static inline tepx_test_message_table_t tepx_test_message_vec_at(tepx_test_message_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(tepx_test_message_table_t, vec, i, 0)
__flatbuffers_table_as_root(tepx_test_message)

__flatbuffers_define_string_field(0, tepx_test_message, id, 0)
__flatbuffers_define_scalar_field(1, tepx_test_message, replica_id, flatbuffers_uint16, uint16_t, UINT16_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* TEPX_READER_H */
